openapi: 3.0.1
info:
  title: <PROJECT_NAME>
  version: 1.0.0
  description: <PROJECT_DESCRIPTION>
  contact:
    name: John Dela Cruz
    email: support@example.com
    url: example.com
servers:
  - url: <DEVELOPMENT_ENVIRONMENT_URL>
    description: Development Server
    variables:
      key:
        default: ""
      secret:
        default: ""
  - url: <STAGING_ENVIRONMENT_URL>
    description: Staging Server
    variables:
      key:
        default: ""
      secret:
        default: ""
  - url: <PRODUCTION_ENVIRONMENT_URL>
    description: Production Server
    variables:
      key:
        default: ""
      secret:
        default: ""
tags:
  - name: PUBLIC
    description: Publicly accessible APIs
paths:
  /auth:
    post:
      tags:
        - PUBLIC
      summary: Authenticate user via email or mobile and password
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
            examples:
              DEFAULT:
                value:
                  username: Pierre15@hotmail.com
                  password: 3678ghrma5
      responses:
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedResponse"
              examples:
                DEFAULT:
                  value:
                    code: 401
                    message: Invalid username and password
          description: Invalid username and password
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundResponse"
              examples:
                DEFAULT:
                  value:
                    code: 404
                    message: Username is not registered
          description: Username is not registered
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParameterErrorResponse"
              examples:
                DEFAULT:
                  value:
                    code: 422
                    message: Parameter Error
                    errors:
                      username: Username is required
                      password: Password is required
          description: Parameter Error
        "423":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaxTriesResponse"
              examples:
                DEFAULT:
                  value:
                    code: 423
                    message: Max attempt was reach please try again later
          description: Max tries was reached
components:
  schemas:
    AccessDeniedResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    BadRequestResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    CreatedResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    DeletedResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    DuplicateResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    MaxTriesResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    NotFoundResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    OtpExpiredResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    ParameterErrorResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    ServerErrorResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    SuccessResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    TokenExpiredResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    UnauthorizedResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    UpdatedResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
      description: ""
    AuthRequest:
      type: object
      properties:
        username:
          type: string
          description: Account email address or mobile number
        password:
          type: string
          description: Account password
      description: ""
    AuthResponse:
      type: object
      properties:
        code:
          type: number
          description: Machine readable code
        message:
          type: number
          description: Human readable message
        data:
          type: object
          properties:
            user:
              type: object
              properties:
                uuid:
                  type: string
                  description: Account ID
                email:
                  type: string
                  description: Account Email address
                mobile:
                  type: string
                  description: Account Mobile number
                name:
                  type: string
                  description: Account Name
              description: User Information
            access_token:
              type: string
              description: Access Token for the account
            refresh_token:
              type: string
              description: Refresh Token for the account
          description: Account data information
      description: ""
