report:
  handler: src/functions/crons/report/handler.execute
  timeout: 300
  memorySize: 1024
  events:
    - schedule:
        rate: cron(0 0 * * ? *) # Executed every 8 AM Asia/Manila
        enabled: true